appname="学吧"
appver="1.3"
appcode="4"
appsdk="21"
path_pattern=""
packagename="wpxiao.study.bar"
theme="Theme_DeviceDefault_Light_DarkActionBar"
app_key=""
app_channel=""
developer="彭文晓"
description=""
debugmode=false
user_permission={
  "ACCESS_NETWORK_STATE",
  "INTERNET",
  "WRITE_EXTERNAL_STORAGE"
}
